global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "sites"
    static_configs:
      - targets: ["localhost:9092"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "site_up"
        action: keep
