global:
  scrape_interval: 1m
  scrape_timeout: 30s

scrape_configs:
  - job_name: "site-monitor"
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: ["localhost:9092"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "site_up"
        action: keep # This ensures we only keep the site_up metric

    relabel_configs:
      - source_labels: [domain, directory]
        action: labelmap
        regex: (.+)
        replacement: $1
