# global:
#   scrape_interval: 1m

# scrape_configs:
#   - job_name: "sites"
#     static_configs:
#       - targets: ["localhost:9092"]
#     metric_relabel_configs:
#       - source_labels: [__name__]
#         regex: "site_up"
#         action: keep

global:
  scrape_interval: 1m
  scrape_timeout: 30s

scrape_configs:
  - job_name: "site-monitor"
    static_configs:
      - targets: ["localhost:9092"]
    honor_labels: true
    metrics_path: "/metrics"
